Description:

    CFN template to provision MariaDb node using ASG

Resources:
   ThoughtworkDataBaseLC:
     Type: AWS::AutoScaling::LaunchConfiguration
     Metadata:
       "AWS::CloudFormation::Init":
         configSets:
            myconf:
               - "set1"
               - "set2"
               - "set3"  
         set1:
           services:
             sysvinit:
               mariadb:
                 enabled: "true"
                 ensureRunning: "true"
      
         set2: 
           commands:
             download_from_s3:
               command: "aws s3 sync s3://sujkub8 /tmp"
             install my-sql python connector:
               command: "~/.local/bin/pip install mysql-connector"

         set3:
           commands:
             #set permission for setupfile:
              # command: "chmod +x /tmp/db_setup.py"
             execute setup file:
               command: "python /tmp/db_setup.py"
     Properties: 
       AssociatePublicIpAddress: True
       ImageId: ami-0e0ff550130b28343
       InstanceType: t2.micro
       KeyName: sujithmelur3
       IamInstanceProfile: s3_admin
       LaunchConfigurationName: TW-DB-LaunchConfiguration
       SecurityGroups:
         - sg-009520ade5ae9b243
       UserData: !Base64
         'Fn::Join':
           - ""
           - - |
              #!/bin/bash -v
             - |
               yum install -y  maria*
             - export CFN_StackId=
             - !Ref 'AWS::StackId'
             - |+

             - export CFN_StackName=
             - !Ref 'AWS::StackName'
             - |+
    
             - export CFN_Region=
             - !Ref 'AWS::Region'
             - |+
             
             - '/opt/aws/bin/cfn-init '
             - '  --stack ${CFN_StackId} '
             - '  --resource ThoughtworkDataBaseLC '
             - '  --region ${CFN_Region} '
             - |2
                  --configsets myconf

   TestASG:
     Type: AWS::AutoScaling::AutoScalingGroup
     Properties: 
       AutoScalingGroupName: ThoughtWork-Db-ASG
       DesiredCapacity: 1
       LaunchConfigurationName: !Ref ThoughtworkDataBaseLC
       MaxSize: 2
       MinSize: 1
       Tags: 
         - Key: Name
           Value: DB-asg
           PropagateAtLaunch: "true"  
       AvailabilityZones:
         Fn::GetAZs: ""        
    
